### ISSUE TITLE
Restore process failed due to "parallel_map" ruby error

### ISSUE THREAD

**Issue by maewonline** [chef/knife-ec-backup#176]
# Version:

Cinc Server 15.6.2
Ruby 2.7.0
knife-ec-backup 3.0.1

# Environment:

Production - Redhat 8.7

# Scenario:

Moving from my old standalone Chef server 12.x to Cinc server 15.
I have successfully taken a backup using "knife ec backup" from the old chef server and I'm getting an error while doing the restore:

# Replication Command
```knife ec restore /opt/old_chef12_backup/ -c /etc/cinc-project/pivotal.rb --webui-key /etc/cinc-project/webui_priv.pem --concurrency 1 -VVV```

# Stacktrace
```
TRACE: BaseFile: got a file path of /opt/old_chef12_backup/organizations/revenue/groups/billing-admins.json for billing-admins.json
TRACE: BaseFile: Detecting file extension for clients
TRACE: BaseFile: got a file path of /opt/old_chef12_backup/organizations/revenue/groups/clients.json for clients.json
TRACE: BaseFile: Detecting file extension for users
TRACE: BaseFile: got a file path of /opt/old_chef12_backup/organizations/revenue/groups/users.json for users.json
Traceback (most recent call last):
        17: from ./knife:23:in `<main>'
        16: from ./knife:23:in `load'
        15: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/knife-17.10.0/bin/knife:24:in `<top (required)>'
        14: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/knife-17.10.0/lib/chef/application/knife.rb:165:in `run'
        13: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/knife-17.10.0/lib/chef/knife.rb:233:in `run'
        12: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/knife-17.10.0/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
        11: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/chef-17.10.0/lib/chef/local_mode.rb:42:in `with_server_connectivity'
        10: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/knife-17.10.0/lib/chef/knife.rb:494:in `block in run_with_pretty_exceptions'
         9: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/knife-ec-backup-3.0.1/lib/chef/knife/ec_restore.rb:57:in `run'
         8: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/knife-ec-backup-3.0.1/lib/chef/knife/ec_restore.rb:136:in `for_each_organization'
         7: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/knife-ec-backup-3.0.1/lib/chef/knife/ec_restore.rb:136:in `foreach'
         6: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/knife-ec-backup-3.0.1/lib/chef/knife/ec_restore.rb:139:in `block in for_each_organization'
         5: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/knife-ec-backup-3.0.1/lib/chef/knife/ec_restore.rb:62:in `block in run'
         4: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/knife-ec-backup-3.0.1/lib/chef/knife/ec_restore.rb:286:in `upload_org_data'
         3: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/knife-ec-backup-3.0.1/lib/chef/knife/ec_restore.rb:286:in `select'
         2: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/chef-17.10.0/lib/chef/chef_fs/file_system.rb:52:in `each'
         1: from /opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/chef-17.10.0/lib/chef/chef_fs/file_system.rb:70:in `list_from'
/opt/cinc-project/embedded/lib/ruby/gems/2.7.0/gems/chef-17.10.0/lib/chef/chef_fs/file_system.rb:75:in `list_from': undefined method `parallel_map' for #<Array:0x0000000004b41f28> (NoMethodError)
```

**Comment by maewonline** [comment]
I tried to use Cinc Server 15.7.0 but the same issue exist

**Comment by maewonline** [comment]
The problem was solved after installing the latest cinc-workstation-23.5 on the cinc-server
